"""Interactive and scriptable generation of validated NEP-kappa inputs."""

from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path

import yaml


PRESETS = ("three-phonon", "four-phonon", "qha", "scph", "qha-sscha")
CALCULATORS = ("nep", "mace", "vasp")


@dataclass(frozen=True)
class InitializerAnswers:
    """Small set of choices needed to create a useful starter input."""

    preset: str
    calculator: str
    structure: str
    model: str | None
    result_dir: str
    dimension: tuple[int, int, int]
    mesh: tuple[int, int, int]
    use_slurm: bool = False
    vasp_command: str = "vasp_std"
    potcar_path: str = "/path/to/potpaw_PBE"
    fourphonon_command: str = "ShengBTE_cpu"


def initialize_input(
    output_path,
    *,
    preset=None,
    calculator=None,
    structure=None,
    model=None,
    result_dir=None,
    dimension=None,
    mesh=None,
    use_slurm=False,
    vasp_command=None,
    potcar_path=None,
    fourphonon_command=None,
    interactive=True,
    overwrite=False,
    input_fn=input,
):
    """Collect choices, validate the generated YAML, and atomically write it."""
    output_path = Path(output_path).expanduser()
    if output_path.suffix.lower() not in {".yaml", ".yml"}:
        raise ValueError("The generated input filename must end in .yaml or .yml.")
    if output_path.exists() and not overwrite:
        raise FileExistsError(
            f"Input file already exists: {output_path}. Use --force to replace it."
        )

    answers = collect_answers(
        preset=preset,
        calculator=calculator,
        structure=structure,
        model=model,
        result_dir=result_dir,
        dimension=dimension,
        mesh=mesh,
        use_slurm=use_slurm,
        vasp_command=vasp_command,
        potcar_path=potcar_path,
        fourphonon_command=fourphonon_command,
        interactive=interactive,
        input_fn=input_fn,
    )
    document = build_input_document(answers)
    text = (
        "# Generated by nepkappa init. Review paths and convergence settings.\n"
        + yaml.safe_dump(document, sort_keys=False)
    )
    output_path.parent.mkdir(parents=True, exist_ok=True)
    temporary = output_path.with_name(
        f".{output_path.stem}.tmp{output_path.suffix}"
    )
    temporary.write_text(text, encoding="utf-8")
    try:
        from nepkappa.config import parse_workflow_args

        parse_workflow_args(temporary, command="run")
    except SystemExit as exc:
        temporary.unlink(missing_ok=True)
        raise ValueError("Generated input failed NEP-kappa validation.") from exc
    except Exception:
        temporary.unlink(missing_ok=True)
        raise
    temporary.replace(output_path)
    return output_path, answers


def collect_answers(
    *,
    preset=None,
    calculator=None,
    structure=None,
    model=None,
    result_dir=None,
    dimension=None,
    mesh=None,
    use_slurm=False,
    vasp_command=None,
    potcar_path=None,
    fourphonon_command=None,
    interactive=True,
    input_fn=input,
):
    """Resolve command options and optional interactive answers."""
    if interactive:
        preset = preset or ask_choice(
            "Calculation preset", PRESETS, default="three-phonon", input_fn=input_fn
        )
        structure = structure or ask_text(
            "Structure file", default="POSCAR", input_fn=input_fn
        )
        calculator = calculator or ask_choice(
            "Force calculator", CALCULATORS, default="nep", input_fn=input_fn
        )
        if calculator == "nep":
            model = model or ask_text(
                "NEP model", default="nep.txt", input_fn=input_fn
            )
        elif calculator == "mace":
            model = model or ask_text(
                "MACE checkpoint or foundation name", default="mp", input_fn=input_fn
            )
        elif calculator == "vasp":
            vasp_command = vasp_command or ask_text(
                "VASP command", default="vasp_std", input_fn=input_fn
            )
            potcar_path = potcar_path or ask_text(
                "POTCAR library", default="/path/to/potpaw_PBE", input_fn=input_fn
            )
        dimension = dimension or ask_int3(
            "Force-constant supercell", default=(3, 3, 3), input_fn=input_fn
        )
        mesh = mesh or ask_int3(
            "Brillouin-zone mesh", default=(21, 21, 21), input_fn=input_fn
        )
        result_dir = result_dir or ask_text(
            "Result directory",
            default=f"calculations/runs/{preset}",
            input_fn=input_fn,
        )
        if preset in {"three-phonon", "four-phonon", "scph", "qha-sscha"}:
            use_slurm = ask_yes_no(
                "Prepare Slurm jobs", default=use_slurm, input_fn=input_fn
            )

    preset = preset or "three-phonon"
    calculator = calculator or "nep"
    structure = structure or "POSCAR"
    result_dir = result_dir or f"calculations/runs/{preset}"
    dimension = _int3(dimension or (3, 3, 3), "dimension")
    mesh = _int3(mesh or (21, 21, 21), "mesh")
    if preset not in PRESETS:
        raise ValueError(f"Unknown preset '{preset}'. Choose from: {', '.join(PRESETS)}")
    if calculator not in CALCULATORS:
        raise ValueError(
            f"Unknown calculator '{calculator}'. Choose from: {', '.join(CALCULATORS)}"
        )
    if calculator == "nep":
        model = model or "nep.txt"
    elif calculator == "mace":
        model = model or "mp"
    if preset in {"qha", "qha-sscha"} and use_slurm:
        raise ValueError(
            "The QHA/QHA+SSCHA initializer does not yet generate internal Slurm jobs. "
            "Submit `nepkappa run` as one batch job instead."
        )
    return InitializerAnswers(
        preset=preset,
        calculator=calculator,
        structure=str(structure),
        model=None if model is None else str(model),
        result_dir=str(result_dir),
        dimension=dimension,
        mesh=mesh,
        use_slurm=bool(use_slurm),
        vasp_command=str(vasp_command or "vasp_std"),
        potcar_path=str(potcar_path or "/path/to/potpaw_PBE"),
        fourphonon_command=str(fourphonon_command or "ShengBTE_cpu"),
    )


def build_input_document(answers):
    """Build one concise, schema-compatible YAML document."""
    dim = list(answers.dimension)
    mesh = list(answers.mesh)
    document = {
        "workflow": {"preset": answers.preset},
        "structure": {"poscar": answers.structure, "dimensionality": 3},
        "calculator": _calculator_section(answers),
        "relaxation": {"enabled": False},
        "force-constant": {"dim-fc2": dim},
        "output": {"progress": True, "result-dir": answers.result_dir},
    }

    if answers.preset in {"three-phonon", "four-phonon", "scph", "qha-sscha"}:
        document["force-constant"].update(
            {"dim-fc3": dim, "compact-fc": True, "format": "phono3py"}
        )
    if answers.use_slurm and answers.preset in {
        "three-phonon",
        "four-phonon",
        "scph",
    }:
        document["force-constant"]["parallel"] = _slurm_defaults(
            "nepkappa-force"
        )

    if answers.preset == "three-phonon":
        document["kappa"] = _kappa_section(mesh)
    elif answers.preset == "four-phonon":
        document["force-constant"].update(
            {"dim-fc4": dim, "format": "both"}
        )
        document["kappa"] = _kappa_section(mesh)
        document["fourphonon"] = _fourphonon_section(answers, mesh, dim)
    elif answers.preset in {"qha", "qha-sscha"}:
        document["qha"] = {
            "volume-ratios": [0.94, 0.97, 1.0, 1.03, 1.06],
            "dim-fc2": dim,
            "mesh": mesh,
            "temps": [0, 1000, 10],
            "eos": "vinet",
            "relax-internal": True,
        }
        if answers.preset == "qha-sscha":
            document["scph"] = {
                "workdir": "phonopy-sscha",
                "temps": [300, 900, 300],
                "snapshots": 200,
                "iterations": 4,
                "transient": 1,
                "sscha-mesh": mesh,
                "run-transport": True,
            }
            document["kappa"] = _kappa_section(mesh, temperatures=[300])
    elif answers.preset == "scph":
        document["scph"] = {
            "workdir": "phonopy-sscha",
            "temps": [300, 900, 300],
            "snapshots": 200,
            "iterations": 4,
            "transient": 1,
            "sscha-mesh": mesh,
            "run-transport": True,
        }
        document["kappa"] = _kappa_section(mesh, temperatures=[300])
    return document


def _calculator_section(answers):
    if answers.calculator == "nep":
        return {"name": "nep", "nep-model": answers.model}
    if answers.calculator == "mace":
        model = str(answers.model)
        section = {"name": "mace", "device": "cpu", "dtype": "float64"}
        if Path(model).suffix or Path(model).exists() or "/" in model:
            section["model"] = model
        else:
            section["foundation"] = model
        return section
    return {
        "name": "vasp",
        "vasp-command": answers.vasp_command,
        "potcar-path": answers.potcar_path,
    }


def _kappa_section(mesh, temperatures=None):
    return {
        "mesh": mesh,
        "temps": temperatures or [100, 1000, 50],
        "method": "rta",
        "isotope": False,
        "bfmp": 1.0e6,
        "wigner": False,
    }


def _fourphonon_section(answers, mesh, dim):
    section = {
        "command": answers.fourphonon_command,
        "workdir": "fourphonon",
        "mesh": mesh,
        "temps": [300, 1000, 100],
        "scell": dim,
        "solver": "rta",
        "sample-3ph": -1,
        "sample-3ph-phase-space": -1,
        "sample-4ph": 10000,
        "sample-4ph-phase-space": 10000,
    }
    if answers.use_slurm:
        section["parallel"] = {
            "backend": "slurm",
            "nodes": 1,
            "ntasks": 4,
            "cpus-per-task": 4,
            "time": "1-00:00:00",
            "job-name": "nepkappa-kappa4",
            "submit": False,
        }
    return section


def _slurm_defaults(job_name):
    return {
        "backend": "slurm",
        "jobs": 16,
        "max-concurrent": 4,
        "cpus-per-task": 1,
        "time": "1-00:00:00",
        "job-name": job_name,
        "submit": False,
    }


def ask_choice(label, choices, *, default, input_fn=input):
    options = "/".join(choices)
    while True:
        answer = input_fn(f"{label} [{options}] ({default}): ").strip()
        value = answer or default
        if value in choices:
            return value
        if value.isdigit() and 1 <= int(value) <= len(choices):
            return choices[int(value) - 1]
        print(f"Choose one of: {', '.join(choices)}")


def ask_text(label, *, default, input_fn=input):
    answer = input_fn(f"{label} ({default}): ").strip()
    return answer or default


def ask_int3(label, *, default, input_fn=input):
    default_text = " ".join(str(value) for value in default)
    while True:
        answer = input_fn(f"{label} ({default_text}): ").strip()
        try:
            return _int3((answer or default_text).replace(",", " ").split(), label)
        except ValueError as exc:
            print(exc)


def ask_yes_no(label, *, default=False, input_fn=input):
    default_text = "Y/n" if default else "y/N"
    while True:
        answer = input_fn(f"{label} [{default_text}]: ").strip().lower()
        if not answer:
            return default
        if answer in {"y", "yes"}:
            return True
        if answer in {"n", "no"}:
            return False
        print("Answer yes or no.")


def _int3(values, label):
    try:
        result = tuple(int(value) for value in values)
    except (TypeError, ValueError) as exc:
        raise ValueError(f"{label} must contain three positive integers.") from exc
    if len(result) != 3 or any(value <= 0 for value in result):
        raise ValueError(f"{label} must contain three positive integers.")
    return result
